// Generated by scripts/generate-phi-console-statics.ts — do not edit by hand.
//
// String literals used in console calls in this project's convex/ source.
// On PHI deployments (VIKTOR_SPACES_PHI_MODE=true) only these compile-time
// constants survive console redaction; every other message is replaced with
// the ***PHI_REDACTED*** sentinel (see phiLogging.ts). The Viktor platform
// regenerates this file from the deployed source before every PHI deploy.
export const PHI_CONSOLE_STATIC_MESSAGES: string[] = [];
