/**
 * PHI console redaction for Viktor Spaces on HIPAA (PHI) deployments.
 *
 * Mirror of the Viktor platform logger's PHI mode (viktor/utils/logger.py):
 * on PHI deployments every Convex console line is aggressively redacted so
 * function logs can never carry PHI. The rules, in order:
 *
 * - Numbers, booleans, and null/undefined never carry PHI and are kept.
 * - A message string is kept only when it is a compile-time constant of the
 *   deployed source (the allowlist in phiConsoleStatics.ts, regenerated by
 *   the Viktor platform before every PHI deploy). Strings built at runtime
 *   (template literals with substitutions, concatenation) may embed user
 *   content and are redacted wholesale.
 * - Errors keep their name and stack frames (frames are code, not data) but
 *   lose their message.
 * - Everything else — runtime strings, objects, arrays — is replaced with
 *   the ***PHI_REDACTED*** sentinel.
 *
 * The shim installs itself only when the deployment env var
 * VIKTOR_SPACES_PHI_MODE is "true" (set by the Viktor platform on PHI
 * deployments); everywhere else console behaves normally. Coverage follows
 * the module graph: this module is imported by the template roots
 * (functions.ts, auth.ts, http.ts), so any function module
 * that uses the template's builders — as all app functions must — is
 * covered.
 */
import { PHI_CONSOLE_STATIC_MESSAGES } from "./phiConsoleStatics";

declare const process: { env: Record<string, string | undefined> };

export const PHI_REDACTED = "***PHI_REDACTED***";
export const PHI_MODE_ENV_VAR = "VIKTOR_SPACES_PHI_MODE";

const DEFAULT_STATIC_MESSAGES: ReadonlySet<string> = new Set(
  PHI_CONSOLE_STATIC_MESSAGES,
);

// Console methods with free-form arguments, per the Convex runtime.
const ARG_METHODS = ["debug", "log", "info", "warn", "error", "trace"] as const;
// Timer methods: the label is the only user-controllable value.
const TIMER_METHODS = ["time", "timeEnd", "timeLog"] as const;

export function phiModeEnabled(): boolean {
  return process.env[PHI_MODE_ENV_VAR] === "true";
}

/**
 * Locals-free, message-free rendering of an Error: the frames are code, the
 * message is not (it routinely embeds row data, emails, etc.).
 */
export function sanitizedErrorPhi(error: Error): string {
  const name = error.name || "Error";
  const stack = typeof error.stack === "string" ? error.stack : "";
  const frames = stack
    .split("\n")
    .filter(line => /^\s+at /.test(line))
    .join("\n");
  return frames
    ? `${name}: ${PHI_REDACTED}\n${frames}`
    : `${name}: ${PHI_REDACTED}`;
}

/**
 * Aggressive single-value redaction: scalars that cannot carry PHI are
 * kept, everything else is redacted wholesale.
 */
export function sanitizeValuePhi(value: unknown): unknown {
  if (value === null || value === undefined) return value;
  const kind = typeof value;
  if (kind === "boolean" || kind === "number" || kind === "bigint") {
    return value;
  }
  if (value instanceof Error) return sanitizedErrorPhi(value);
  return PHI_REDACTED;
}

/**
 * Redact one console call's arguments. The first argument is the message
 * slot: a string survives only when it is a compile-time constant of the
 * deployed source; anything else goes through the value rules.
 */
export function sanitizeConsoleArgsPhi(
  args: unknown[],
  statics: ReadonlySet<string> = DEFAULT_STATIC_MESSAGES,
): unknown[] {
  if (args.length === 0) return args;
  const [message, ...rest] = args;
  const sanitizedMessage =
    typeof message === "string"
      ? statics.has(message)
        ? message
        : `<dynamic message> ${PHI_REDACTED}`
      : sanitizeValuePhi(message);
  return [sanitizedMessage, ...rest.map(sanitizeValuePhi)];
}

/** Timer labels survive only as compile-time constants, like messages. */
export function sanitizeTimerLabelPhi(
  label: unknown,
  statics: ReadonlySet<string> = DEFAULT_STATIC_MESSAGES,
): unknown {
  if (typeof label !== "string") return sanitizeValuePhi(label);
  return statics.has(label) ? label : PHI_REDACTED;
}

type ConsoleLike = Record<string, unknown>;

/**
 * Wrap the console methods of `target` with the PHI sanitizers. Wrapping is
 * output-idempotent: sanitizing already-sanitized arguments changes nothing.
 */
export function installPhiConsoleShim(
  target: ConsoleLike = console as unknown as ConsoleLike,
  statics: ReadonlySet<string> = DEFAULT_STATIC_MESSAGES,
): void {
  for (const method of ARG_METHODS) {
    const original = target[method];
    if (typeof original !== "function") continue;
    const bound = (original as (...args: unknown[]) => void).bind(target);
    target[method] = (...args: unknown[]) =>
      bound(...sanitizeConsoleArgsPhi(args, statics));
  }
  for (const method of TIMER_METHODS) {
    const original = target[method];
    if (typeof original !== "function") continue;
    const bound = (original as (...args: unknown[]) => void).bind(target);
    target[method] = (label?: unknown, ...args: unknown[]) =>
      label === undefined
        ? bound()
        : bound(
            sanitizeTimerLabelPhi(label, statics),
            ...args.map(sanitizeValuePhi),
          );
  }
}

if (phiModeEnabled()) {
  installPhiConsoleShim();
}
